### ISSUE TITLE
Save State Bug

### ISSUE THREAD

**Issue by ScratchCat458** [lukebeck/renshu#1]
Bug: Progress save is sometimes randomly removed/changed upon loading.
Exceptions: Reverts when options GUI is opened or when page is reloaded.
Important Notes: Only affects list selection.

**Comment by BypassNeon** [comment]
Possible Solution: Save different save data in separate cookies.

Cookie 1: Active Lists
Cookie 2: Deck State and Score
Cookie 3: Hiragana or Katakana and Recall or Recognition State
